// Code generated by accessory; DO NOT EDIT.

package test

func (t *Tester) GetField1() string {
	if t == nil {
		return ""
	}
	return t.field1
}

func (t *Tester) SetField1(val string) {
	if t == nil {
		return
	}
	t.field1 = val
}

